export const addCart= "Add To Cart"
export const removeCart = "Remove Cart Item"
export const increaseQuantity = "Increase Cart Items Quantity"
export const decreaseQuantity = "Decrease Cart Items Quanitity"
export const totalPrice = "Total Price"